Traceback (most recent call last):
  File "c:\Users\rafael.luna\Desktop\docs pessoais\Projects\BotBlaze\BotBlaze\Bot_v2.py", line 737, in <module>
    model = load_model(ModelPath)
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rafael.luna\AppData\Local\anaconda3\envs\BotBlaze\Lib\site-packages\keras\src\saving\saving_api.py", line 254, in load_model
    return saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rafael.luna\AppData\Local\anaconda3\envs\BotBlaze\Lib\site-packages\keras\src\saving\saving_lib.py", line 281, in load_model
    raise e
  File "C:\Users\rafael.luna\AppData\Local\anaconda3\envs\BotBlaze\Lib\site-packages\keras\src\saving\saving_lib.py", line 269, in load_model
    _load_state(
  File "C:\Users\rafael.luna\AppData\Local\anaconda3\envs\BotBlaze\Lib\site-packages\keras\src\saving\saving_lib.py", line 466, in _load_state
    _load_container_state(
  File "C:\Users\rafael.luna\AppData\Local\anaconda3\envs\BotBlaze\Lib\site-packages\keras\src\saving\saving_lib.py", line 534, in _load_container_state
    _load_state(
  File "C:\Users\rafael.luna\AppData\Local\anaconda3\envs\BotBlaze\Lib\site-packages\keras\src\saving\saving_lib.py", line 435, in _load_state
    trackable.load_own_variables(weights_store.get(inner_path))
  File "C:\Users\rafael.luna\AppData\Local\anaconda3\envs\BotBlaze\Lib\site-packages\keras\src\engine\base_layer.py", line 3531, in load_own_variables
    raise ValueError(
ValueError: Layer 'dense_1' expected 2 variables, but received 0 variables during loading. Expected: ['dense_1/kernel:0', 'dense_1/bias:0']
